server:
  port: ${PORT_USUARIOS}

spring:
  cloud:
    config:
      enabled: false
  application:
    name: user-service
  datasource:
    url: ${URL_DB_USUARIOS}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-minutes: 120

restaurants:
  service:
    url: ${URL_SERVICIO_RESTAURANTES}