server:
  port: 8081
spring:
  cloud:
    config:
      enabled: false
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_usuarios
    username: root
    password: Password
  jpa:
    hibernate:
      ddl-auto: update
security:
  jwt:
    secret: ${JWT_SECRET:clavesecretaparamicroserviciosdeplazoletadedecomidas}
    expiration-minutes: 120

restaurants:
  service:
    url: http://localhost:8080/api/v1/restaurantEmployee
