server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/usuarios
    username: root
    password: Password
  jpa:
    hibernate:
      ddl-auto: update